// Baut demo.json — die Daten der Vorfuehrung unter demo.html.
//
//     node dev/demo-daten.js
//
// Die Helden entstehen aus newChar() der Anwendung: so fehlt kein Feld,
// und eine neue Eigenschaft im Bogen taucht beim naechsten Lauf von
// selbst auf. Wer die Vorfuehrung aendern will, aendert diese Datei und
// laesst sie laufen — demo.json von Hand zu bearbeiten geht auch, aber
// dann sind die beiden auseinander.
const fs = require('fs');
const q = fs.readFileSync('js/data.js', 'utf8') + '\n' + fs.readFileSync('js/util.js', 'utf8');
const namen = [...q.matchAll(/^const ([A-Za-z_$][A-Za-z0-9_$]*)/gm)].map(m => m[1]);
eval(q + ';globalThis.M = {' + namen.join(', ') + '};');
Object.assign(globalThis, M);

const held = (o) => ({...newChar(), adventure: 'demo', ...o});
const fx = (target, value, mode) => ({id: 'e' + Math.random().toString(36).slice(2, 7),
  target, mode: mode || 'bonus', value});

const helden = [
  held({
    id: 'h-brunhilde', name: 'Brunhilde Eisenfaust', race: 'Bergzwergin',
    charClass: 'Kämpfer', subclass: 'Champion', level: 5, background: 'Soldatin',
    str: 16, dex: 12, con: 16, int: 10, wis: 13, cha: 8,
    hp: 38, maxHp: 44, speed: 7.5, profBonus: 3, inspiration: 1,
    savingThrowProfs: ['str', 'con'],
    skillProfs: ['athletik', 'einschuechtern', 'ueberleben'],
    languages: ['Gemeinsprache', 'Zwergisch'],
    toolProfs: ['Schmiedewerkzeug', 'Würfelspiel'],
    weaponProfs: ['Einfache Waffen', 'Kriegswaffen'],
    armorProfs: ['Leicht', 'Mittel', 'Schwer', 'Schilde'],
    stickyFields: ['ac', 'initiative', 'speed', 'profBonus', 'hp'],
    weapons: [
      {...newWeapon(), id: 'w-hammer', name: 'Kriegshammer des Vaters', attrKey: 'str',
       damage: '1W8', damageType: 'Wucht', range: '1,5 m', attackBonus: 1,
       properties: ['Vielseitig'],
       description: 'Nachgeschmiedet aus dem, was vom Original übrig war. Der Kopf trägt eine Runenkerbe, die niemand mehr lesen kann.',
       effects: []},
      {...newWeapon(), id: 'w-beil', name: 'Wurfbeil', attrKey: 'str',
       damage: '1W6', damageType: 'Hieb', range: '6 / 18 m',
       properties: ['Leicht', 'Wurfwaffe'], description: '', effects: []},
    ],
    inventory: [
      {...newItem(), id: 'i-kette', name: 'Kettenpanzer', weight: '25', gearKind: 'ruestung',
       armorType: 'heavy', baseAC: 16, description: 'Schwer, laut, und sie schläft darin.'},
      {...newItem(), id: 'i-schild', name: 'Schild', weight: '3', gearKind: 'schild',
       armorType: 'shield', baseAC: 2, description: ''},
      {...newItem(), id: 'i-trank', name: 'Trank der Heilung', qty: 2, weight: '0,25',
       rarity: 'gewöhnlich', description: 'Heilt 2W4 + 2 Trefferpunkte.'},
      {...newItem(), id: 'i-seil', name: 'Seil aus Hanf (15 m)', weight: '5'},
    ],
    gear: {ruestung: {k: 'i', id: 'i-kette'}, nebenhand: {k: 'i', id: 'i-schild'},
           haupthand: {k: 'w', id: 'w-hammer'}},
    currency: {pp: 0, gp: 48, ep: 0, sp: 6, cp: 2},
    features: [
      {id: 'f-b1', name: 'Zweiter Wind', source: 'Kämpfer 1',
       description: 'Als Bonusaktion 1W10 + Stufe Trefferpunkte zurück. Einmal je Rast.',
       effects: [], effectsActive: true},
      {id: 'f-b2', name: 'Kampfstil: Verteidigung', source: 'Kämpfer 1',
       description: 'Solange sie eine Rüstung trägt: +1 auf die Rüstungsklasse.',
       effects: [fx('ac', 1)], effectsActive: true},
      {id: 'f-b3', name: 'Aktionsschub', source: 'Kämpfer 2',
       description: 'Eine zusätzliche Aktion in ihrem Zug. Einmal je Rast.',
       effects: [], effectsActive: true},
      {id: 'f-b4', name: 'Verbesserter Kritischer Treffer', source: 'Champion 3',
       description: 'Ihre Angriffe treffen schon bei einer 19 kritisch.',
       effects: [], effectsActive: true},
      {id: 'f-b5', name: 'Zwergische Zähigkeit', source: 'Bergzwergin',
       description: 'Vorteil auf Rettungswürfe gegen Gift, und halber Schaden davon.',
       effects: [], effectsActive: true},
    ],
    resources: [
      {id: 'r-b1', name: 'Zweiter Wind', max: 1, used: 1, color: '#c9a84c', restType: 'kurz'},
      {id: 'r-b2', name: 'Aktionsschub', max: 1, used: 0, color: '#a85c3c', restType: 'kurz'},
    ],
    notes: 'Sucht die, die ihren Clan aus Eisenfurt vertrieben haben. Trinkt nicht, seit sie weiß, warum.',
    notesList: [
      {id: 'n-b1', title: 'Der Müller lügt', tags: ['Spur'],
       content: 'Er sagt, die Mühle stehe seit dem Frühjahr still. Das Mehl in der Kammer ist keine zwei Wochen alt.'},
    ],
  }),

  held({
    id: 'h-daemmerlicht', name: 'Dämmerlicht', race: 'Waldelfe',
    charClass: 'Waldläufer', subclass: 'Jägerin', level: 4, background: 'Außenseiterin',
    str: 10, dex: 18, con: 14, int: 11, wis: 15, cha: 9,
    hp: 27, maxHp: 34, speed: 10.5, profBonus: 2,
    savingThrowProfs: ['str', 'dex'],
    skillProfs: ['heimlichkeit', 'ueberleben', 'aufmerksamkeit', 'natur'],
    expertiseProfs: [],
    languages: ['Gemeinsprache', 'Elfisch'],
    toolProfs: [],
    weaponProfs: ['Einfache Waffen', 'Kriegswaffen'],
    armorProfs: ['Leicht', 'Mittel', 'Schilde'],
    weapons: [
      {...newWeapon(), id: 'w-bogen', name: 'Langbogen', attrKey: 'dex',
       damage: '1W8', damageType: 'Stich', range: '45 / 180 m',
       properties: ['Zweihändig', 'Munition'],
       description: 'Aus Mondholz. Der Griff ist mit dem Haar ihrer Schwester umwickelt.',
       effects: []},
      {...newWeapon(), id: 'w-kurz', name: 'Kurzschwert', attrKey: 'fin',
       damage: '1W6', damageType: 'Stich', range: '1,5 m',
       properties: ['Finesse', 'Leicht'], description: '', effects: []},
    ],
    inventory: [
      {...newItem(), id: 'i-leder', name: 'Lederrüstung', weight: '5', gearKind: 'ruestung',
       armorType: 'light', baseAC: 11, description: ''},
      {...newItem(), id: 'i-umhang', name: 'Umhang der Elfen', weight: '0,5',
       rarity: 'selten', gearKind: 'umhang', effectsActive: false,
       effects: [fx('adv_stealth', 0)],
       description: 'Wer ihn trägt, verschwindet im Unterholz, sobald er stillsteht.'},
      {...newItem(), id: 'i-koecher', name: 'Köcher mit 20 Pfeilen', weight: '0,5'},
      {...newItem(), id: 'i-ration', name: 'Reiserationen', qty: 6, weight: '1'},
    ],
    gear: {ruestung: {k: 'i', id: 'i-leder'}, umhang: {k: 'i', id: 'i-umhang'},
           haupthand: {k: 'w', id: 'w-bogen'}},
    currency: {pp: 0, gp: 12, ep: 0, sp: 14, cp: 8},
    features: [
      {id: 'f-d1', name: 'Erzfeind: Untote', source: 'Waldläufer 1',
       description: 'Vorteil auf Überlebenskunst, um ihre Spuren zu lesen, und auf Intelligenzwürfe, um sich an sie zu erinnern.',
       effects: [], effectsActive: true},
      {id: 'f-d2', name: 'Kampfstil: Bogenschießen', source: 'Waldläufer 2',
       description: '+2 auf Angriffswürfe mit Fernkampfwaffen.',
       effects: [], effectsActive: true},
      {id: 'f-d3', name: 'Wildnisläuferin', source: 'Waldläufer 1',
       description: 'Schwieriges Gelände in ihrer bevorzugten Landschaft hält die Gruppe nicht auf.',
       effects: [], effectsActive: true},
      {id: 'f-d4', name: 'Maskerade der Wildnis', source: 'Waldläufer 3',
       description: 'Sie kann versuchen, sich zu verbergen, wenn sie nur leicht verdeckt ist.',
       effects: [], effectsActive: true},
    ],
    spells: [
      {...newSpell(), id: 's-d1', name: 'Jagdzeichen', level: 1, school: 'Weissagung',
       castingTime: '1 Bonusaktion', range: '27 m', components: 'V',
       duration: 'Konzentration, bis zu 1 Stunde',
       description: 'Sie wählt eine Kreatur in Reichweite und zeichnet sie als Beute. Bis der Zauber endet, richtet sie 1W6 zusätzlichen Schaden an, wenn sie das Ziel mit einer Waffe trifft.'},
      {...newSpell(), id: 's-d2', name: 'Ranken', level: 1, school: 'Beschwörung',
       castingTime: '1 Aktion', range: '9 m', components: 'V, S', duration: '10 Minuten',
       description: 'Dichtes Gestrüpp überzieht ein Quadrat von 6 m Kantenlänge und macht es zu schwierigem Gelände.'},
      {...newSpell(), id: 's-d3', name: 'Heilende Berührung', level: 1, school: 'Hervorrufung',
       castingTime: '1 Aktion', range: 'Berührung', components: 'V, S', duration: 'Sofort',
       prepared: false,
       description: 'Eine Kreatur, die sie berührt, erhält 1W8 + Weisheitsmodifikator Trefferpunkte zurück.'},
    ],
    spellSlots: {1: {max: 3, used: 1}, 2: {max: 0, used: 0}, 3: {max: 0, used: 0},
                 4: {max: 0, used: 0}, 5: {max: 0, used: 0}, 6: {max: 0, used: 0},
                 7: {max: 0, used: 0}, 8: {max: 0, used: 0}, 9: {max: 0, used: 0}},
    notes: 'Spricht wenig. Wenn sie spricht, dann über Spuren.',
    notesList: [],
  }),

  held({
    id: 'h-alvara', name: 'Alvara Sonnenhand', race: 'Mensch',
    charClass: 'Kleriker', subclass: 'Lebensdomäne', level: 4, background: 'Gelehrte',
    str: 13, dex: 10, con: 14, int: 12, wis: 17, cha: 11,
    hp: 25, maxHp: 31, tempHp: 4, speed: 9, profBonus: 2,
    savingThrowProfs: ['wis', 'cha'],
    skillProfs: ['religion', 'medizin', 'einblick', 'geschichte'],
    languages: ['Gemeinsprache', 'Himmlisch', 'Zwergisch'],
    toolProfs: ['Kräuterkundeset'],
    weaponProfs: ['Einfache Waffen'],
    armorProfs: ['Leicht', 'Mittel', 'Schilde', 'Schwer'],
    weapons: [
      {...newWeapon(), id: 'w-kolben', name: 'Streitkolben', attrKey: 'str',
       damage: '1W6', damageType: 'Wucht', range: '1,5 m', properties: [],
       description: '', effects: []},
    ],
    inventory: [
      {...newItem(), id: 'i-schuppen', name: 'Schuppenpanzer', weight: '22.5',
       gearKind: 'ruestung', armorType: 'medium', baseAC: 14, description: ''},
      {...newItem(), id: 'i-schild2', name: 'Schild mit Sonnenzeichen', weight: '3',
       gearKind: 'schild', armorType: 'shield', baseAC: 2,
       description: 'Das Zeichen ist frisch aufgemalt. Der Schild darunter ist es nicht.'},
      {...newItem(), id: 'i-symbol', name: 'Heiliges Symbol', weight: '0,5',
       gearKind: 'hals', description: ''},
      {...newItem(), id: 'i-weih', name: 'Weihwasser', qty: 2, weight: '0,5',
       description: 'Als Aktion werfen: 2W6 gleißender Schaden gegen Untote.'},
    ],
    gear: {ruestung: {k: 'i', id: 'i-schuppen'}, nebenhand: {k: 'i', id: 'i-schild2'},
           hals: {k: 'i', id: 'i-symbol'}, haupthand: {k: 'w', id: 'w-kolben'}},
    currency: {pp: 1, gp: 22, ep: 0, sp: 0, cp: 0},
    features: [
      {id: 'f-a1', name: 'Jüngerin des Lebens', source: 'Lebensdomäne 1',
       description: 'Ein Heilzauber vom 1. Grad oder höher gibt zusätzlich 2 + Grad Trefferpunkte zurück.',
       effects: [], effectsActive: true},
      {id: 'f-a2', name: 'Kanal göttlicher Macht: Erhaltung des Lebens',
       source: 'Lebensdomäne 2',
       description: 'Sie verteilt Trefferpunkte in Höhe des Fünffachen ihrer Klassenstufe an Kreaturen im Umkreis von 9 m — höchstens bis zur Hälfte ihres Maximums.',
       effects: [], effectsActive: true},
      {id: 'f-a3', name: 'Untote vertreiben', source: 'Kleriker 2',
       description: 'Jeder Untote im Umkreis von 9 m muss einen Weisheitsrettungswurf bestehen oder eine Minute lang fliehen.',
       effects: [], effectsActive: true},
      {id: 'f-a4', name: 'Schwere Rüstung', source: 'Lebensdomäne 1',
       description: 'Übung mit schwerer Rüstung.', effects: [], effectsActive: true},
    ],
    spells: [
      {...newSpell(), id: 's-a1', name: 'Licht', level: 0, school: 'Hervorrufung',
       castingTime: '1 Aktion', range: 'Berührung', components: 'V, M', duration: '1 Stunde',
       description: 'Ein Gegenstand leuchtet wie eine Fackel.'},
      {...newSpell(), id: 's-a2', name: 'Heiliger Funke', level: 0, school: 'Hervorrufung',
       castingTime: '1 Aktion', range: '18 m', components: 'V, S', duration: 'Sofort',
       description: 'Das Ziel muss einen Geschicklichkeitsrettungswurf bestehen oder erleidet 1W8 gleißenden Schaden.'},
      {...newSpell(), id: 's-a3', name: 'Heilendes Wort', level: 1, school: 'Hervorrufung',
       castingTime: '1 Bonusaktion', range: '18 m', components: 'V', duration: 'Sofort',
       description: 'Eine Kreatur, die sie sehen kann, erhält 1W4 + Zaubermodifikator Trefferpunkte zurück.'},
      {...newSpell(), id: 's-a4', name: 'Segnen', level: 1, school: 'Verzauberung',
       castingTime: '1 Aktion', range: '9 m', components: 'V, S, M',
       duration: 'Konzentration, bis zu 1 Minute',
       description: 'Bis zu drei Kreaturen würfeln 1W4 zusätzlich auf jeden Angriffswurf und jeden Rettungswurf.'},
      {...newSpell(), id: 's-a5', name: 'Schild des Glaubens', level: 1, school: 'Bannmagie',
       castingTime: '1 Bonusaktion', range: '18 m', components: 'V, S, M',
       duration: 'Konzentration, bis zu 10 Minuten', prepared: false,
       description: 'Eine Kreatur erhält +2 auf die Rüstungsklasse.'},
      {...newSpell(), id: 's-a6', name: 'Geistige Waffe', level: 2, school: 'Hervorrufung',
       castingTime: '1 Bonusaktion', range: '18 m', components: 'V, S',
       duration: '1 Minute',
       description: 'Eine schwebende Waffe aus Kraft greift als Bonusaktion an: 1W8 + Zaubermodifikator Energieschaden.'},
      {...newSpell(), id: 's-a7', name: 'Person heilen', level: 2, school: 'Hervorrufung',
       castingTime: '1 Aktion', range: 'Berührung', components: 'V, S', duration: 'Sofort',
       description: 'Eine Kreatur erhält 70 Trefferpunkte zurück und wird von Blindheit, Taubheit und Krankheit befreit.'},
    ],
    spellSlots: {1: {max: 4, used: 2}, 2: {max: 3, used: 1}, 3: {max: 0, used: 0},
                 4: {max: 0, used: 0}, 5: {max: 0, used: 0}, 6: {max: 0, used: 0},
                 7: {max: 0, used: 0}, 8: {max: 0, used: 0}, 9: {max: 0, used: 0}},
    resources: [
      {id: 'r-a1', name: 'Kanal göttlicher Macht', max: 1, used: 0,
       color: '#e0c040', restType: 'kurz'},
    ],
    notes: 'Kam wegen der Bibliothek. Bleibt wegen der Leute.',
    notesList: [
      {id: 'n-a1', title: 'Was im Keller stand', tags: ['Rätsel'],
       content: 'Der Kreis auf dem Boden ist kein Beschwörungskreis. Er hält etwas drinnen, nicht draußen.'},
    ],
  }),

  held({
    id: 'h-fitz', name: 'Fitz Wieselflink', race: 'Halbling (Leichtfuß)',
    charClass: 'Schurke', subclass: 'Meuchler', level: 4, background: 'Gassenkind',
    str: 8, dex: 18, con: 12, int: 14, wis: 12, cha: 14,
    hp: 22, maxHp: 27, speed: 7.5, profBonus: 2,
    savingThrowProfs: ['dex', 'int'],
    skillProfs: ['heimlichkeit', 'fingerfert', 'taueschen', 'akrobatik',
                 'nachforschung', 'aufmerksamkeit'],
    expertiseProfs: ['heimlichkeit', 'fingerfert'],
    languages: ['Gemeinsprache', 'Halblingisch', 'Diebessprache'],
    toolProfs: ['Diebeswerkzeug', 'Kartenspiel'],
    weaponProfs: ['Einfache Waffen', 'Handarmbrust', 'Langschwert', 'Rapier', 'Kurzschwert'],
    armorProfs: ['Leicht'],
    weapons: [
      {...newWeapon(), id: 'w-rapier', name: 'Rapier', attrKey: 'fin',
       damage: '1W8', damageType: 'Stich', range: '1,5 m', properties: ['Finesse'],
       description: '', effects: []},
      {...newWeapon(), id: 'w-armbrust', name: 'Handarmbrust', attrKey: 'dex',
       damage: '1W6', damageType: 'Stich', range: '9 / 36 m',
       properties: ['Leicht', 'Munition', 'Nachladen'], description: '', effects: []},
      {...newWeapon(), id: 'w-dolch', name: 'Dolch', attrKey: 'fin',
       damage: '1W4', damageType: 'Stich', range: '1,5 m',
       properties: ['Finesse', 'Leicht', 'Wurfwaffe'], description: '', effects: []},
    ],
    inventory: [
      {...newItem(), id: 'i-leder2', name: 'Lederrüstung', weight: '5',
       gearKind: 'ruestung', armorType: 'light', baseAC: 11, description: ''},
      {...newItem(), id: 'i-diebe', name: 'Diebeswerkzeug', weight: '0,5',
       description: 'Feilen, Dietriche, ein kleiner Spiegel an einem Stiel.'},
      {...newItem(), id: 'i-bolzen', name: 'Armbrustbolzen', qty: 20, weight: '0,05'},
      {...newItem(), id: 'i-ring', name: 'Silberring mit Wappen', weight: '0',
       rarity: 'gewöhnlich',
       description: 'Gehört jemandem, der ihn noch nicht vermisst.'},
    ],
    gear: {ruestung: {k: 'i', id: 'i-leder2'}, haupthand: {k: 'w', id: 'w-rapier'},
           fernkampf: {k: 'w', id: 'w-armbrust'}},
    currency: {pp: 0, gp: 6, ep: 3, sp: 41, cp: 77},
    features: [
      {id: 'f-f1', name: 'Verstohlener Angriff (2W6)', source: 'Schurke 1',
       description: 'Einmal je Zug 2W6 zusätzlichen Schaden, wenn er Vorteil hat oder ein Verbündeter neben dem Ziel steht.',
       effects: [], effectsActive: true},
      {id: 'f-f2', name: 'Gerissene Aktion', source: 'Schurke 2',
       description: 'Als Bonusaktion spurten, zurückziehen oder verstecken.',
       effects: [], effectsActive: true},
      {id: 'f-f3', name: 'Meuchelmörder', source: 'Meuchler 3',
       description: 'Vorteil gegen alles, was noch nicht gehandelt hat. Ein Treffer gegen einen Überraschten ist ein kritischer Treffer.',
       effects: [], effectsActive: true},
      {id: 'f-f4', name: 'Glückspilz', source: 'Halbling',
       description: 'Eine 1 auf dem W20 darf er einmal neu würfeln.',
       effects: [], effectsActive: true},
    ],
    resources: [
      {id: 'r-f1', name: 'Glückspilz heute genutzt', max: 3, used: 1,
       color: '#7fb3d5', restType: 'tag'},
    ],
    notes: 'Zählt beim Reden das Geld der anderen mit. Nicht aus Absicht — es geht einfach von selbst.',
    notesList: [],
  }),
];

// ── Die Bibliothek der Gruppe ────────────────────────────────────
const bibliothek = {
  _adventures: [{id: 'demo', name: 'Die Mühle am Schwarzbach'}],
  _laeden: {
    demo: {
      name: 'Bogens Krämerladen', kauf: 0.4,
      waren: [
        {id: 'lw1', name: 'Fackel', preis: 1, notiz: 'brennt eine Stunde'},
        {id: 'lw2', name: 'Seil aus Hanf (15 m)', preis: 100, notiz: ''},
        {id: 'lw3', name: 'Reiserationen', preis: 50, notiz: 'einen Tag'},
        {id: 'lw4', name: 'Trank der Heilung', preis: 5000, notiz: 'letztes Stück'},
        {id: 'lw5', name: 'Kletterausrüstung', preis: 2500, notiz: ''},
        {id: 'lw6', name: 'Öl (Krug)', preis: 10, notiz: ''},
        {id: 'lw7', name: 'Weihwasser', preis: 2500, notiz: 'kommt vom Kloster, dauert'},
        {id: 'lw8', name: 'Winterumhang', preis: 500, notiz: ''},
      ],
    },
  },
  item: [
    {...newItem(), id: 'db1', name: 'Trank der Heilung', weight: '0,25',
     rarity: 'gewöhnlich', description: 'Heilt 2W4 + 2 Trefferpunkte. Eine Aktion.'},
    {...newItem(), id: 'db2', name: 'Fackel', weight: '0,5',
     description: 'Brennt eine Stunde und leuchtet 6 m weit hell.'},
    {...newItem(), id: 'db3', name: 'Weihwasser', weight: '0,5',
     description: 'Als improvisierte Wurfwaffe: 2W6 gleißender Schaden gegen Untote und Unholde.'},
  ],
};

// ── Die Beute ────────────────────────────────────────────────────
const beute = {
  titel: 'Aus der Truhe im Keller der Mühle',
  muenzen: {pp: 0, gp: 184, ep: 0, sp: 62, cp: 40},
  stuecke: [
    {id: 'b1', name: 'Ring des Schutzes', anzahl: 1,
     notiz: 'schimmert blau, wenn Magie in der Nähe ist'},
    {id: 'b2', name: 'Trank der Heilung', anzahl: 3, notiz: ''},
    {id: 'b3', name: 'Silberleuchter', anzahl: 2, notiz: 'im Wert von je 25 Gold'},
    {id: 'b4', name: 'Mühlenbuch, wasserfleckig', anzahl: 1,
     notiz: 'die letzten zwölf Seiten sind herausgerissen',
     an: 'h-alvara', anName: 'Alvara Sonnenhand'},
  ],
};

// ── Der Kampf, wie ihn die Runde sieht ───────────────────────────
const kampf = {
  name: 'Am Mühlrad', phase: 'kampf', aktiv: true, runde: 3, zug: 0, gezeigt: true,
  karte: {
    breite: 14, hoehe: 9, feldMeter: 1.5, zeigen: true,
    gelaende: [
      '..###....TT...',
      '..#..#...T....',
      '..#..+....~~~~',
      '..####....~~~~',
      '.........x~~~~',
      '..........~~~~',
      '.T........~~~~',
      'TT.....//.~~~~',
      '..............',
    ].join(''),
    figuren: {
      t1: {x: 4, y: 4, k: 'Br'},
      t2: {x: 3, y: 6, k: 'Al'},
      t3: {x: 2, y: 7, k: 'Dä'},
      t4: {x: 5, y: 5, k: 'Fi'},
      t5: {x: 8, y: 3, k: 'g1'},
      t6: {x: 9, y: 5, k: 'g2'},
      t7: {x: 7, y: 1, k: 'An', h: 3},
    },
  },
  teilnehmer: [
    {id: 't3', art: 'held', charId: 'h-daemmerlicht', ini: 21,
     zustaende: [], erschoepfung: 0, vorteil: true, nachteil: false},
    {id: 't5', art: 'gegner', name: 'Ghul', ini: 18, zustaende: [],
     zustand: 'Angeschlagen', balken: 0.55, erschoepfung: 0},
    {id: 't1', art: 'held', charId: 'h-brunhilde', ini: 14,
     zustaende: ['Gepackt'], erschoepfung: 0, vorteil: false, nachteil: false},
    {id: 't4', art: 'held', charId: 'h-fitz', ini: 13,
     zustaende: [], erschoepfung: 0, vorteil: false, nachteil: false},
    {id: 't6', art: 'gegner', name: 'Ghul', ini: 11, zustaende: ['Verängstigt'],
     zustand: 'Schwer verwundet', balken: 0.18, erschoepfung: 0},
    {id: 't2', art: 'held', charId: 'h-alvara', ini: 9,
     zustaende: [], erschoepfung: 0, vorteil: false, nachteil: false},
    {id: 't7', art: 'gegner', name: 'Etwas über dem Mühlrad', ini: 6,
     zustaende: [], zustand: 'Unversehrt', balken: 1, erschoepfung: 0},
  ],
  log: [],
};

const raus = {
  hinweis: 'Vorführdaten für demo.html — erfundene Helden, kein echter Spielstand.',
  konto: {id: 'demo-spieler', name: 'Gast',
          gruppen: [{session_code: 'DEMO', rolle: 'spieler'}], ist_admin: false},
  bibliothek, helden, beute, kampf,
};

fs.writeFileSync('demo.json', JSON.stringify(raus, null, 2) + '\n');
console.log('demo.json geschrieben:',
  Math.round(fs.statSync('demo.json').size / 1024) + ' KB, '
  + helden.length + ' Helden');
